---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-stack
  labels:
    toolkit.fluxcd.io/tenant: monitoring
---
# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: prometheus-stack
spec:
  interval: 60m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: prometheus-stack
spec:
  releaseName: prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        namespace: prometheus-stack
        name: prometheus-community
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values: {}
  # matchLabels and matchExpressions are always ANDed and so we need to match our release label
    # prometheus:
    #   prometheusSpec:
    #     serviceMonitorSelector:
    #       # matchLabels:
    #       #   release: prometheus-stack
    #       matchExpressions:
    #       - { key: release, operator: In, values: [prometheus-stack] }
    #       # - { key: monitor, operator: In, values: [prometheus-stack] }
