---
# Enable secret PUSH from dbs to dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-secret-receive-from-dbs
namespace: dev
resources:
  - ../../eso_enable_receive_secrets.yaml
patches:
- target:
    kind: RoleBinding
  patch: |
    - op: replace
      path: /metadata/name
      value: es-store-role-from-dbs-to-dev
    - op: add
      path: /subjects/-
      value:
        kind: ServiceAccount
        name: sa-externalsecret
        namespace: dbs
