---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps-auth
resources:
  - dbs_enable_push_secrets
  # - auth_enable_push_secrets
  # - auth-keycloak.yaml
  # - auth-master-realm-sa.yaml
