---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps-dev
resources:
  # - dbs_send_push_secrets
  # - dev_secret_receive_from_dbs
  - auth_send_push_secrets
  - dev_secret_receive_from_auth
  - dev_enable_receive_secrets
  - service-cap
  - ns.yaml
