---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-secret-push-from-auth
namespace: auth
resources:
  - ../../base/eso_enable_push_secrets.yaml
patches:
  - target:
      kind: RoleBinding
    patch: |
      - op: add
        path: /subjects/-
        value:
          kind: ServiceAccount
          name: sa-externalsecret
          namespace: auth
