---
# Enable secret PUSH from auth to dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-secret-receive
namespace: dev
resources:
  - ../../eso_enable_receive_secrets.yaml
