---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
  interval: 5m
  path: ./ingress
  prune: true
