---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  targetNamespace: istio-ingress
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: istio-system
  interval: 5m
  path: ./clusters/home-k8s/istio/ingress
  prune: true
