---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: auth-receive-secrets-from-dbs
resources:
  - ../../eso_receive_secrets.yaml
namespace: auth
nameSuffix: -from-dbs
patches:
  - target:
      kind: RoleBinding
    patch: |
      - op: add
        path: /subjects/-
        value:
          kind: ServiceAccount
          name: sa-externalsecret
          namespace: dbs
