---
# Enable secret PUSH from auth to dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-secret-receive-from-auth
namespace: dev
resources:
  - ../../eso_enable_receive_secrets.yaml
nameSuffix: -from-auth
patches:
  - target:
      kind: RoleBinding
    patch: |
      - op: add
        path: /subjects/-
        value:
          kind: ServiceAccount
          name: sa-externalsecret
          namespace: auth
