---
# Enable secret PUSH from auth to dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-secret-receive-from-auth
namespace: dev
resources:
  - ../../../base/eso_enable_receive_secrets.yaml
patches:
  - target:
      kind: RoleBinding
    patch: |
      - op: replace
        path: /metadata/name
        value: es-store-role-from-auth-to-dev
      - op: add
        path: /subjects/-
        value:
          kind: ServiceAccount
          name: sa-externalsecret
          namespace: auth
