---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-send_push_secrets
resources:
  - ../../eso_send_push_secrets.yaml
namespace: auth
nameSuffix: -dev-ns
patches:
  - target:
      kind: SecretStore
    patch: |
      - op: replace
        path: /spec/provider/kubernetes/remoteNamespace
        value: dev
